### ISSUE TITLE
grid16_0 fehlt bei Pixel Grid

### ISSUE THREAD

**Issue by BugBuster1701** [BugBuster1701/contao_grid_16_columns#2]
``` css
/**
 * For 100% wide, without margin, not within an article
 * e.g. for HTML Modules in header 
 */
.grid16_0 {
    margin: 0 !important;
    width: 100%;
}
```
