### ISSUE TITLE
Another small bug in responsive.css (or grid.css)...

### ISSUE THREAD

**Issue by BugBuster1701** [BugBuster1701/contao_grid_16_columns#5]
adaptieren.
contao bug #5584

``` css
*[class*="grid"] { 
    float:none !important; 
    display:block !important; 
    width:auto !important; 
} 
```
