### ISSUE TITLE
C3.1 : Offset Klassen gehen nicht mehr wenn man die Änderungen übernimmt

### ISSUE THREAD

**Issue by BugBuster1701** [BugBuster1701/contao_grid_16_columns#7]
durch diese Änderung:

``` css
.mod_article [class*="ce_"], .mod_article [class*="mod_"] {
    margin-left: 10px;
    margin-right: 10px;
}
```

funktionieren die offset Klassen nicht mehr.
siehe [Forum](https://community.contao.org/de/showthread.php?42364-12-Spalten-Grid-Offset-Klasse-funktioniert-nicht&p=273466&viewfull=1#post273466)
